[package]
name = "scrib"
version = "0.1.0"
authors = ["Yuta Taniguchi <yuta.taniguchi.y.t@gmail.com>"]

[dependencies]
actix-web = "0.6"
log = "0.4"
env_logger = "0.5"
rust-crypto = "0.2"
serde = "1.0"
serde_derive = "1.0"
structopt = "0.2"
