[package]
name = "scrib"
version = "0.1.0"
authors = ["Yuta Taniguchi <yuta.taniguchi.y.t@gmail.com>"]

[dependencies]
docopt = "0.6"
rust-crypto = "0.2"
rustc-serialize = "0.3"
serde = "0.7"
serde_json = "0.7"
iron = "0.3"
router = "0.1"
handlebars = "0.16"
handlebars-iron = "0.15"

[features]
watch = ["handlebars-iron/watch"]
