[package]
name = "scrib"
version = "0.1.0"
authors = ["Yuta Taniguchi <yuta.taniguchi.y.t@gmail.com>"]

[dependencies]
docopt = "0.6.*"
rust-crypto = "*"
rustc-serialize = "0.3"
iron = "*"
router = "*"
handlebars = "*"
handlebars-iron = "*"

[features]
watch = ["handlebars-iron/watch"]
